In [1]:
pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [2]:
import pandas as pd
import random
from sklearn import linear_model
import numpy as np

In [3]:
titanic = pd.read_csv('train.csv')

In [4]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.5+ KB


In [5]:
titanic['Pclass'].describe()

count    891.000000
mean       2.308642
std        0.836071
min        1.000000
25%        2.000000
50%        3.000000
75%        3.000000
max        3.000000
Name: Pclass, dtype: float64

In [6]:
titanic['Pclass'].hist()

In [7]:
sample = random.sample(list(titanic.index), 10)

In [8]:
sample

[795, 782, 380, 246, 780, 250, 10, 182, 204, 216]

In [9]:
len(titanic.index)/2

445.5

In [10]:
sample = random.sample(list(titanic.index), int(len(titanic.index)*.75))

In [11]:
training_data = titanic.loc[sample]
test_data = titanic.drop(sample)

In [12]:
regr_object = linear_model.LinearRegression()

In [13]:
regr_object.fit(training_data[['Pclass']], training_data['Survived'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
len(training_data['Pclass'].dropna())

668

In [15]:
len(training_data['Survived'].dropna())

668

In [16]:
regr_object.coef_

array([-0.18779678])

In [17]:
np.mean((regr_object.predict(training_data[['Pclass']]) - training_data['Survived']) ** 2)

0.20905770777653801

In [18]:
prediction = regr_object.predict(test_data[['Pclass']])

In [19]:
prediction[prediction > 0.5] = 1

In [20]:
prediction[prediction <= 0.5] = 0

In [21]:
counts = prediction == test_data['Survived']

In [22]:
len(counts[counts==True])/len(counts)

0.6636771300448431

# Adding Additional Variables to Regression

In [23]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'], dtype='object')

In [24]:
new_regr_object = linear_model.LinearRegression()

In [26]:
training_data.loc[training_data['Sex'] == 'male', 'Sex'] = 1

In [27]:
test_data.loc[test_data['Sex'] == 'male', 'Sex'] = 1

In [28]:
training_data.loc[training_data['Sex'] == 'female', 'Sex'] = 0

In [29]:
test_data.loc[test_data['Sex'] == 'female', 'Sex'] = 0

In [30]:
new_regr_object.fit(training_data[['Pclass', 'Sex']], training_data['Survived'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [31]:
new_regr_object.coef_

array([-0.15366126, -0.51258475])

In [32]:
np.mean((new_regr_object.predict(training_data[['Pclass', 'Sex']]) - training_data['Survived']) ** 2)

0.15018352415865271

In [33]:
new_prediction = new_regr_object.predict(test_data[['Pclass','Sex']])

In [35]:
new_prediction[new_prediction > 0.5] = 1

In [36]:
new_prediction[new_prediction <= 0.5] = 0

In [37]:
new_counts = new_prediction == test_data['Survived']

In [38]:
new_counts.value_counts()

True     176
False     47
dtype: int64

In [40]:
len(new_counts[new_counts==True])/len(new_counts)

0.7892376681614349

# Adding 3rd Variable to Model

In [63]:
training_data = training_data[training_data['Age'].notnull()]

In [64]:
third_regr_object = linear_model.LinearRegression()

In [65]:
third_regr_object.fit(training_data[['Pclass', 'Sex', 'Age']], training_data['Survived'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [66]:
third_regr_object.coef_

array([-0.19363984, -0.47826344, -0.00572132])

In [73]:
np.mean((third_regr_object.predict(training_data[['Pclass', 'Sex', 'Age']]) - training_data['Survived']) ** 2)

0.1457203015131982

In [74]:
test_data = test_data[test_data['Age'].notnull()]

In [75]:
third_prediction = third_regr_object.predict(test_data[['Pclass','Sex', 'Age']])

In [77]:
third_prediction[third_prediction > 0.5] = 1

In [78]:
third_prediction[third_prediction <= 0.5] = 0

In [79]:
third_counts = third_prediction == test_data['Survived']

In [81]:
third_counts.value_counts()

True     141
False     40
dtype: int64

In [83]:
len(third_counts[third_counts==True])/len(third_counts)

0.7790055248618785

# Other Models

In [84]:
from sklearn import svm

In [85]:
svm_object = svm.SVC()

In [86]:
svm_object.fit(training_data[['Pclass', 'Sex', 'Age']], training_data['Survived'])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [87]:
svm_prediction = svm_object.predict(test_data[['Pclass','Sex', 'Age']])

In [88]:
svm_prediction[svm_prediction > 0.5] = 1

In [89]:
svm_prediction[svm_prediction <= 0.5] = 0

In [90]:
svm_counts = svm_prediction == test_data['Survived']

In [91]:
svm_counts.value_counts()

True     136
False     45
dtype: int64