In [20]:
pylab

<module 'matplotlib.pylab' from '/Users/sanajaved/.virtualenvs/dataanalysis/lib/python3.4/site-packages/matplotlib/pylab.py'>

In [21]:
import pandas as pd
import random
from sklearn import linear_model
import numpy as np

In [22]:
titanic = pd.read_csv('train.csv')

In [23]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.5+ KB


In [24]:
titanic['Pclass'].describe()

count    891.000000
mean       2.308642
std        0.836071
min        1.000000
25%        2.000000
50%        3.000000
75%        3.000000
max        3.000000
Name: Pclass, dtype: float64

In [25]:
titanic['Pclass'].hist()

In [26]:
sample = random.sample(list(titanic.index), 10)

In [27]:
sample

[599, 779, 793, 39, 210, 635, 401, 164, 515, 259]

In [28]:
len(titanic.index)/2

445.5

In [29]:
sample = random.sample(list(titanic.index), int(len(titanic.index)*.75))

In [30]:
training_data = titanic.loc[sample]
test_data = titanic.drop(sample)

In [31]:
regr_object = linear_model.LinearRegression()

In [32]:
regr_object.fit(training_data[['Pclass']], training_data['Survived'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [33]:
len(training_data['Pclass'].dropna())

668

In [34]:
len(training_data['Survived'].dropna())

668

In [35]:
regr_object.coef_

array([-0.20299195])

In [36]:
np.mean((regr_object.predict(training_data[['Pclass']]) - training_data['Survived']) ** 2)

0.20747085106129073

In [37]:
prediction = regr_object.predict(test_data[['Pclass']])

In [38]:
prediction[prediction > 0.5] = 1

In [39]:
prediction[prediction <= 0.5] = 0

In [41]:
counts = prediction == test_data['Survived']

In [42]:
len(counts[counts==True])/len(counts)

0.6412556053811659

# Adding Additional Variables to Regression

In [44]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'], dtype='object')

In [46]:
new_regr_object = linear_model.LinearRegression()

In [47]:
new_regr_object.fit(training_data[['Pclass', 'Sex']], training_data['Survived'])

ValueError: could not convert string to float: 'male'

In [63]:
training_data.loc[training_data['Sex'] == 'male', 'Sex'] = 1

In [71]:
test_data.loc[test_data['Sex'] == 'male', 'Sex'] = 1

In [64]:
training_data.loc[training_data['Sex'] == 'female', 'Sex'] = 0

In [72]:
test_data.loc[test_data['Sex'] == 'female', 'Sex'] = 0

In [66]:
new_regr_object.fit(training_data[['Pclass', 'Sex']], training_data['Survived'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [67]:
new_regr_object.coef_

array([-0.16261804, -0.53385587])

In [68]:
np.mean((new_regr_object.predict(training_data[['Pclass', 'Sex']]) - training_data['Survived']) ** 2)

0.14425760354918052

In [73]:
new_prediction = new_regr_object.predict(test_data[['Pclass','Sex']])

In [74]:
new_prediction

array([ 0.78338907,  0.94600711,  0.08691516,  0.78338907,  0.24953319,
        0.62077103,  0.62077103,  0.08691516,  0.94600711,  0.08691516,
        0.62077103,  0.78338907,  0.08691516,  0.08691516,  0.62077103,
        0.08691516,  0.94600711,  0.78338907,  0.41215123,  0.78338907,
        0.08691516,  0.41215123,  0.78338907,  0.62077103,  0.08691516,
        0.08691516,  0.08691516,  0.24953319,  0.41215123,  0.08691516,
        0.41215123,  0.41215123,  0.41215123,  0.08691516,  0.08691516,
        0.08691516,  0.08691516,  0.41215123,  0.08691516,  0.08691516,
        0.08691516,  0.41215123,  0.62077103,  0.62077103,  0.08691516,
        0.24953319,  0.78338907,  0.08691516,  0.41215123,  0.24953319,
        0.62077103,  0.41215123,  0.08691516,  0.08691516,  0.94600711,
        0.08691516,  0.08691516,  0.08691516,  0.08691516,  0.62077103,
        0.78338907,  0.08691516,  0.24953319,  0.08691516,  0.08691516,
        0.24953319,  0.62077103,  0.94600711,  0.24953319,  0.78

In [75]:
new_prediction[new_prediction > 0.5] = 1

In [76]:
new_prediction[new_prediction <= 0.5] = 0

array([ 1.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,
        0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,
        1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,
        0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,
        0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,
        0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  0

In [78]:
new_counts = new_prediction == test_data['Survived']

In [79]:
new_counts.value_counts()

True     170
False     53
dtype: int64

In [81]:
len(new_counts[new_counts==True])/len(new_counts)

0.7623318385650224